image: python:3.9

before_script:
  - pip install -r requirements.txt
  - pip install sphinx pydata-sphinx-theme

pages:
  script:
    - sphinx-build -b html docs/source/ docs/build/html/
  artifacts:
    paths:
      - docs/build/html/
