name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master  # Change 'main' to 'master' if you're using 'master' as the default branch

permissions:
  contents: write   # Permet de pousser les modifications sur le dépôt
  pages: write      # Permet de déployer sur GitHub Pages
  id-token: write   # Nécessaire pour l'authentification via GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install sphinx pydata-sphinx-theme

    - name: Build documentation
      run: sphinx-build -b html docs/source/ public/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # This is the branch where your docs will be deployed
        folder: public  # The folder containing the generated docs
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to allow deployment
